---
name: 'Build'

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: "17 6 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node and Yarn
        uses: volta-cli/action@v4

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: HACS build validation
        uses: "hacs/action@21.12.1"
        with:
          category: "plugin"

          # Don't attempt to load into HACS (as it loads the release, not the
          # build).
          ignore: "hacs"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: frigate-hass-card
          path: dist/*.js
